"""实时面试结束后生成可下载 Markdown 总结报告。"""
from datetime import datetime
from typing import Dict, List, Optional

from core.llm_service import generate_ai_review, score_three_six_dimensions


def _hire_level(total: int) -> str:
    if total >= 90:
        return "✅ 优先录用"
    if total >= 80:
        return "📌 拟录用"
    if total >= 70:
        return "📋 储备录用"
    return "❌ 暂不录用"


def build_interview_markdown(
    session_id: str,
    job_title: str,
    transcript: List[Dict[str, str]],
    started_at: Optional[datetime] = None,
    dialog_id: Optional[str] = None,
    resume_text: str = "",
) -> str:
    """根据对话记录 + LLM 复盘生成 Markdown 报告。"""
    started_at = started_at or datetime.now()
    dialogue_md = "\n\n".join(
        f"### {item['role']} `{item.get('time', '')}`\n\n{item['text']}"
        for item in transcript
    )
    plain = "\n".join(f"{item['role']}：{item['text']}" for item in transcript)

    ai_report = ""
    score_result = {"总分": 0, "评价": "无有效对话内容"}
    if plain.strip() and len(plain.strip()) >= 20:
        ai_report = generate_ai_review(plain)
        score_result = score_three_six_dimensions(plain)

    total = score_result.get("总分", 0)
    hire = _hire_level(total)
    three = score_result.get("三性评分", {})
    six = score_result.get("六讲评分", {})
    resume_block = ""
    if (resume_text or "").strip():
        resume_block = f"""
---

## 附：候选人简历摘要

{(resume_text or '').strip()[:3000]}

"""

    md = f"""# 实时面试总结报告

| 项目 | 内容 |
|------|------|
| 会话 ID | `{session_id}` |
| 百炼 Dialog ID | `{dialog_id or '-'}` |
| 应聘岗位 | **{job_title}** |
| 面试开始 | {started_at.strftime('%Y-%m-%d %H:%M:%S')} |
| 报告生成 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} |
| 三性六讲总分 | **{total} 分** |
| 录用建议 | {hire} |

---

## 一、对话实录

{dialogue_md if dialogue_md else '_（无有效对话记录）_'}

---

## 二、三性六讲评分

| 维度 | 得分 |
|------|------|
| 专业性 | {three.get('专业性', '-')} |
| 逻辑性 | {three.get('逻辑性', '-')} |
| 完整性 | {three.get('完整性', '-')} |
| 讲痛点 | {six.get('讲痛点', '-')} |
| 讲方案 | {six.get('讲方案', '-')} |
| 讲落地 | {six.get('讲落地', '-')} |
| 讲数据 | {six.get('讲数据', '-')} |
| 讲价值 | {six.get('讲价值', '-')} |
| 讲反思 | {six.get('讲反思', '-')} |

**综合评价：** {score_result.get('评价', '')}

---

## 三、AI 深度复盘

{ai_report if ai_report else '_内容过短，无法生成复盘。_'}

---

## 四、录用判定说明

- **评级：** {hire}
- **依据：** 基于整场实时对话转写与三性六讲量化评分综合判定
- **说明：** 本报告由百炼实时多模态面试 + 通义千问复盘自动生成，供 HR/候选人复盘参考

---

*Generated by AI Interview System — Live Interview Module*
"""
    return md + resume_block
